export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REVISION_SELECTED = 'REVISION_SELECTED';
export const DOCUMENTATION_SELECTED = 'DOCUMENTATION_SELECTED';
export const DOCUMENTATION_LIST_UPDATE = 'DOCUMENTATION_LIST_UPDATE';
export const DOCUMENTATION_EMPTY = 'DOCUMENTATION_EMPTY';
export const CHANGES_UPDATE = 'CHANGES_UPDATE';
