// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const TOKENS_RECEIVED = 'TOKENS_RECEIVED';

// DOCU
export const REVISION_SELECTED = 'REVISION_SELECTED';
export const DOCUMENTATION_SELECTED = 'DOCUMENTATION_SELECTED';
export const DOCUMENTATION_LIST_UPDATE = 'DOCUMENTATION_LIST_UPDATE';
export const DOCUMENTATION_EMPTY = 'DOCUMENTATION_EMPTY';
export const CHANGES_UPDATE = 'CHANGES_UPDATE';

// EDIT
export const PAGE_AUTOSAVE = 'PAGE_AUTOSAVE';
export const PAGE_AUTOSAVE_REMOVE = 'PAGE_AUTOSAVE_REMOVE';
